### ISSUE TITLE
Version in API

### ISSUE THREAD

**Issue by adrianocanofre** [adrianocanofre/flask-template#5]
Create  versioning for APIs.

Ex:
api/v1/service
api/v2/service

**Comment by NinoDoko** [comment]
I wanna take this on. Is there a specific idea you have in mind? As in, how is versioning defined? In the `config.py` file, YAML files or somewhere else?

**Comment by adrianocanofre** [comment]
I think this would be a good solution.
https://cbron.github.io/blog/2014/07/03/versioning-a-flask-restful-api/

Replay the service.py and create a behave.
